c = int (input ('Quantas séries você realiza de costas semanalmente? '))
p = int (input ('Quantas séries você realiza de peito semanalmente?: '))      
b = int (input ('Quantas séries você realiza de bíceps semanalmente?: '))
t = int (input ('Quantas séries você realiza de tríceps semanalmente?: '))
p1 = int (input ('Quantas séries você realiza para quadríceps semanalmente?: '))
p2 = int (input ('Quantas séries você realiza para posterior de coxa semanalmente?: '))
g = int (input ('Quantas séries você realiza para glúteos semanalmente?: '))
p3 = int (input ('Quantas séries você realiza para panturrilha semanalmente?: '))
print (f'Você realiza {c+p+b+t} séries para superiores semanalmente')
print (f'Você realiza {p1+p2+g+p3} séries para inferiores')